application: octohaven
version: 0-1-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
# resources handlers
- url: /style/(.*\.(|css|eot|otf|svg|ttf|woff|woff2))$
  static_files: static/css/\1
  upload: static/css/(.*\.(css|eot|otf|svg|ttf|woff|woff2))$

- url: /script/(js|coffee)/(.*\.(js|coffee))$
  static_files: static/\1/\2
  upload: static/(.*?)/(.*\.(js|coffee))$

- url: /font/(.*\.(ttf))$
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.(ttf))$

# images
- url: /image/(.*\.(ico|png|jpg|jpeg))$
  static_files: static/img/\1
  upload: static/img/(.*\.(ico|png|jpg|jpeg))$


# webpage handlers
- url: /api/.*
  script: api.application

- url: /auth/.*
  script: auth.application

- url: /.*
  script: app.application


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$


libraries:
- name: webapp2
  version: latest
# using official connector
#- name: mysql.connector
#  version: 2.0.4
