// Generated by CoffeeScript 1.9.0
(function() {
  var Template;

  Template = (function() {
    function Template(_at_settings) {
      this.settings = _at_settings != null ? _at_settings : {};
      this.correct(this.settings);
    }

    Template.prototype.set = function(key, value) {
      if (value !== null) {
        return this.settings[key] = value.toString();
      } else {
        return null;
      }
    };

    Template.prototype.get = function(key) {
      if (key in this.settings) {
        return this.settings[key];
      } else {
        return null;
      }
    };

    Template.prototype.exists = function(key) {
      return this.get(key) !== null;
    };

    Template.prototype.correct = function() {
      var key, value, _ref, _results;
      _ref = this.settings;
      _results = [];
      for (key in _ref) {
        value = _ref[key];
        _results.push(this.set(key, value));
      }
      return _results;
    };

    return Template;

  })();

  if (this.Template == null) {
    this.Template = Template;
  }

}).call(this);
