// Generated by CoffeeScript 1.9.0
(function() {
  var add, canvas, del, form;

  form = document.getElementById("octohaven-editor-form");

  if (!form) {
    throw new Error("Form is undefined");
  }

  canvas = new this.Canvas(form);

  add = new this.Control("+ module", (function(_this) {
    return function(itself) {
      return canvas.addModule(new _this.Module);
    };
  })(this));

  del = new this.Control("- module", function(itself) {
    return console.log(itself);
  });

  canvas.addControl(add);

  canvas.addControl(del);

}).call(this);
