// Generated by CoffeeScript 1.9.0
(function() {
  var STATUS_BUSY, STATUS_PENDING, STATUS_READY, STATUS_UNREACHABLE, requestStatus, serverMasterAddress, serverStatus, serverUIAddress, setMasterAddress, setStatus, setUIAddress;

  serverStatus = document.getElementById("octohaven-spark-server-status");

  serverUIAddress = document.getElementById("octohaven-spark-ui-address");

  serverMasterAddress = document.getElementById("octohaven-spark-master-address");

  if (!(serverStatus && serverUIAddress && serverMasterAddress)) {
    throw new Error("Server entries are unrecognized");
  }

  STATUS_PENDING = "Pending...";

  STATUS_READY = "Server is ready";

  STATUS_BUSY = "Server is busy";

  STATUS_UNREACHABLE = "Server is unreachable";

  setStatus = function(status) {
    serverStatus.className = "";
    if (status === false) {
      serverStatus.innerHTML = "" + STATUS_PENDING;
      return this.util.addClass(serverStatus, "text-mute");
    } else if (status === 0) {
      this.util.addClass(serverStatus, "text-green");
      return serverStatus.innerHTML = "" + STATUS_READY;
    } else if (status === -1) {
      this.util.addClass(serverStatus, "text-yellow");
      return serverStatus.innerHTML = "" + STATUS_BUSY;
    } else {
      this.util.addClass(serverStatus, "text-red");
      return serverStatus.innerHTML = "" + STATUS_UNREACHABLE;
    }
  };

  setUIAddress = function(address) {
    if (address) {
      return serverUIAddress.innerHTML = "" + address;
    } else {
      return serverUIAddress.innerHTML = "?";
    }
  };

  setMasterAddress = function(address) {
    if (address) {
      return serverMasterAddress.innerHTML = "" + address;
    } else {
      return serverMasterAddress.innerHTML = "?";
    }
  };

  requestStatus = function() {
    var masterAddress, status, uiAddress, _ref;
    _ref = [false, false, false], status = _ref[0], uiAddress = _ref[1], masterAddress = _ref[2];
    setStatus(status);
    return this.loader.sendrequest("get", "/api/v1/sparkstatus", {}, null, (function(_this) {
      return function(code, response) {
        var json;
        if (code === 200) {
          json = JSON.parse(response);
          status = json["content"]["sparkstatus"];
          uiAddress = json["content"]["spark-ui-address"];
          masterAddress = json["content"]["spark-master-address"];
        } else {
          console.log("[ERROR] " + response);
        }
        setStatus(status);
        setUIAddress(uiAddress);
        return setMasterAddress(masterAddress);
      };
    })(this), (function(_this) {
      return function(error, response) {
        setStatus(false);
        setUIAddress(false);
        setMasterAddress(false);
        return console.log("[ERROR] " + response);
      };
    })(this));
  };

  if (typeof requestStatus === "function") {
    requestStatus();
  }

}).call(this);
