// Generated by CoffeeScript 1.9.0
(function() {
  var blankslate, blankslateWithMsg, column, contentHeader, contentList, contentValue, jobDetailsElem, jobid, property, row, searchstr, view, _jobloader, _mapper, _ref, _util,
    __slice = [].slice;

  jobDetailsElem = document.getElementById("octohaven-job-details");

  if (!jobDetailsElem) {
    throw new Error("Job details element is not found");
  }

  _mapper = this.mapper;

  _util = this.util;

  _jobloader = new this.JobLoader;

  blankslate = function(internal) {
    var blankview;
    blankview = _mapper.parseMapForParent({
      type: "div",
      cls: "blankslate"
    });
    _mapper.parseMapForParent(internal, blankview);
    return blankview;
  };

  blankslateWithMsg = function(header, msg) {
    var body;
    header = {
      type: "h1",
      cls: "text-thin",
      title: "" + header
    };
    body = {
      type: "p",
      title: "" + msg
    };
    return blankslate([header, body]);
  };

  contentHeader = function(value) {
    return {
      type: "span",
      cls: "text-mute",
      title: "" + value
    };
  };

  contentValue = function(value) {
    return {
      type: "span",
      title: "" + value
    };
  };

  contentList = function(list) {
    var x, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      x = list[_i];
      _results.push({
        type: "p",
        children: {
          type: "span",
          title: "" + x
        }
      });
    }
    return _results;
  };

  column = function(content, islarge) {
    var col, updatedClass;
    if (islarge == null) {
      islarge = false;
    }
    updatedClass = islarge ? "four-fifths column" : "one-fifth column";
    col = {
      type: "div",
      cls: "" + updatedClass,
      children: content
    };
    return _mapper.parseMapForParent(col);
  };

  property = function() {
    var cols, prop, x;
    cols = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    prop = {
      type: "div",
      cls: "columns",
      children: [
        (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = cols.length; _i < _len; _i++) {
            x = cols[_i];
            _results.push(x);
          }
          return _results;
        })()
      ]
    };
    return _mapper.parseMapForParent(prop);
  };

  row = function(property) {
    var rw;
    rw = {
      type: "div",
      cls: "segment",
      children: property
    };
    return _mapper.parseMapForParent(rw);
  };

  if (!(window.location && window.location.search)) {
    throw new Error("Window.location is not set properly");
  }

  searchstr = (_ref = window.location.search) != null ? _ref.trim().split("=") : void 0;

  if (_util.isArray(searchstr) && searchstr.length === 2) {
    jobid = searchstr[1];
    _jobloader.getJob(jobid, function() {
      return jobDetailsElem.innerHTML = "";
    }, function(ok, json) {
      var create, entrypoint, jar, job, jobconf, masterurl, msg, name, options, rowsElem, status, submit, view, x, y;
      if (ok) {
        job = json["content"]["job"];
        name = job["sparkjob"]["name"];
        status = job["status"];
        entrypoint = job["sparkjob"]["entrypoint"];
        masterurl = job["sparkjob"]["masterurl"];
        options = (function() {
          var _ref1, _results;
          _ref1 = job["sparkjob"]["options"];
          _results = [];
          for (x in _ref1) {
            y = _ref1[x];
            _results.push(x + " = " + y);
          }
          return _results;
        })();
        jobconf = (function() {
          var _i, _len, _ref1, _results;
          _ref1 = job["sparkjob"]["jobconf"];
          _results = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            x = _ref1[_i];
            _results.push("" + x);
          }
          return _results;
        })();
        jar = job["sparkjob"]["jar"];
        create = job["createtime"];
        submit = job["submittime"];
        rowsElem = {
          type: "div",
          cls: "segments",
          children: [
            row(property(column(contentHeader("Spark job name"), false), column(contentValue(name), true))), row(property(column(contentHeader("Created"), false), column({
              type: "span",
              title: "" + (_util.timestampToDate(create))
            }, true))), row(property(column(contentHeader("Expected run"), false), column({
              type: "span",
              title: "" + (_util.timestampToDate(submit))
            }, true))), row(property(column(contentHeader("Status"), false), column(contentValue(status), true))), row(property(column(contentHeader("Entrypoint"), false), column(contentValue(entrypoint), true))), row(property(column(contentHeader("Spark URL"), false), column(contentValue(masterurl), true))), row(property(column(contentHeader("Jar file"), false), column(contentValue(jar), true))), row(property(column(contentHeader("Options"), false), column(contentList(options), true))), row(property(column(contentHeader("Job conf"), false), column(contentList(jobconf), true)))
          ]
        };
        return _mapper.parseMapForParent(rowsElem, jobDetailsElem);
      } else {
        msg = json ? json["content"]["msg"] : "We know and keep working on that";
        view = blankslateWithMsg("Something went wrong", msg);
        return _mapper.parseMapForParent(view, jobDetailsElem);
      }
    });
  } else {
    jobDetailsElem.innerHTML = "";
    view = blankslateWithMsg("Something went wrong", "We know and keep working on that");
    _mapper.parseMapForParent(view, jobDetailsElem);
  }

}).call(this);
